name: Build and Release Bubblewrap

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libcap-dev libseccomp-dev libtool meson pkg-config

      - name: Build Bubblewrap
        run: |
          bash build.sh

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bwrap-linux-x64
          path: src/_builddir/bwrap

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: bwrap-linux-x64
          path: release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/bwrap
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
